# Site settings
title: Derek
SEOTitle: 呆·博
header-img: img/header-auroal-new.jpg
email: litianyangchn@gmail.com
description: "Thoughts, imaginations, and stories."
keyword: "Thoughts, imaginations, stories"
url: "https://deeeeeeeerek.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "A student from University of Toronto, major in Economics and Mathematics, comajor with Statistics."
sidebar-avatar: /img/sidebar-avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
# github_username:    
# facebook_username:  
# jianshu_username:   
# twitter_username:   



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: markdown                            # use Github Flavored Markdown !important

# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e8c784e006b7bdbf0f46    #生成的clientID
  clientSecret: 90c671bcfa1c9108418b2616df9a9a5bc950f182    #生成的clientSecret
  repo: Deeeeeeeerek.github.io    #仓库名称
  owner: Deeeeeeeerek    #github用户名
  admin: Deeeeeeeerek
  distractionFreeMode: true    #是否启用类似FB的阴影遮罩



# 统计
# Analytics settings
# Google Analytics
ga_track_id: 'UA-135665911-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
# friends: [
#     {
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]